# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bigfact blog
email: bigfact@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
    He says, 'Hello World'!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.bigfact.cc" # the base hostname & protocol for your site
# twitter_username: bigfact0
github_username: bigfact

# Build settings
# markdown: kramdown
# highlighter: rouge
# highlighter: pygments
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# auto: true
